# Site settings
title: Fang (Frank) Sun
SEOTitle: 孙昉的博客 | FSun Blog
header-img: img/home-bg.jpg
email: fs3unu@virginia.edu
description: "这里是孙昉的博客，一个有一点小抱负的理想主义未来智慧建筑师 | 斜杠青年本人"
keyword: "孙昉, Frank, Frank Sun, 建筑, 设计, 计算机, 智慧城市, 智慧建筑"
url: "https://blog.fangfranksun.com" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: huxpro
zhihu_username: huxpro
github_username: huxpro
twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

disqus:
  comments: true  # boolean type, the global switch for posts comments.
  shortname: 'fsunblog'  
# Disqus settings
#disqus_username: fangfranksun

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-JMC0KLTP7S" # Format: UA-xxxxxx-xx
ga_domain: blog.fangfranksun.com

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Build NOW, Build FUTURE."
sidebar-avatar: https://github.com/fangfranksun.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
